---
- hosts: jenkins-slave
  become: true 
  tasks: 
  - name: update ubuntu repo and cache 
    apt: 
      update_cache: yes 
      cache_valid_time: 3600 

  - name: Remove Java 17 if installed
    apt:
       name: openjdk-17-jdk
       state: absent

  - name: install java
    apt:
      name: openjdk-11-jdk
      state: present

  - name: Set Java 11 as default
    alternatives:
       name: java
       path: /usr/lib/jvm/java-11-openjdk-amd64/bin/java

  - name: Download Maven package
    get_url:
      url: https://archive.apache.org/dist/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz
      dest: /opt

  - name: extract maven packages 
    unarchive:
      src: /opt/apache-maven-3.9.2-bin.tar.gz
      dest: /opt 
      remote_src: yes